/* EPC independent multi-timer control panel. No writes to event/accounting records. */
(function(){
const KEY='epcTimersV1',defaults=[[100,200,200,20],[200,400,400,20],[300,600,600,20],[400,800,800,20]];
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch(e){return []}};
const set=a=>{localStorage.setItem(KEY,JSON.stringify(a));window.epcTimerRender()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','"':'&quot;',"'":'&#39;'}[c]));
window.epcTimers_=get;
window.epcTimerAdd=function(){const a=get();a.push({id:'clock-'+Date.now(),name:'賽事計時器 '+(a.length+1),eventId:'',levels:defaults.map(x=>x.slice()),index:0,remaining:1200,running:false,deadline:0,pool:'',announcement:'',ticker:''});set(a)};
window.epcTimerDelete=function(id){if(!confirm('刪除此計時器設定？'))return;set(get().filter(t=>t.id!==id))};
window.epcTimerChange=function(id,k,v){const a=get(),t=a.find(t=>t.id===id);if(!t)return;t[k]=v;if(k==='index'){t.remaining=t.levels[+v]?.[3]*60||1200;t.running=false}set(a)};
window.epcTimerAction=function(id,act){const a=get(),t=a.find(t=>t.id===id);if(!t)return;const now=Date.now();if(act==='toggle'){if(t.running){t.remaining=Math.max(0,Math.ceil((t.deadline-now)/1000));t.running=false}else{t.running=true;t.deadline=now+Math.max(1,t.remaining)*1000}}if(act==='reset'){t.running=false;t.remaining=t.levels[t.index]?.[3]*60||1200}if(act==='next'||act==='prev'){t.running=false;t.index=Math.max(0,Math.min(t.levels.length-1,t.index+(act==='next'?1:-1)));t.remaining=t.levels[t.index]?.[3]*60||1200}set(a)};
window.epcTimerLevels=function(id,value){const a=get(),t=a.find(t=>t.id===id);if(!t)return;const levels=value.split('\n').map(x=>x.split(/[,，\s/]+/).map(Number)).filter(x=>x.length>=4&&x.slice(0,4).every(Number.isFinite)&&x[3]>0).map(x=>x.slice(0,4));if(!levels.length)return alert('請輸入：小盲,大盲,前注,分鐘，每行一級');t.levels=levels;t.index=0;t.remaining=levels[0][3]*60;t.running=false;set(a)};
window.epcTimerRender=function(){const box=document.getElementById('epcTimerList');if(!box)return;const a=get(),events=(typeof db!=='undefined'&&Array.isArray(db.events)?db.events:[]);box.innerHTML=a.length?a.map(t=>{const ev=events.find(e=>String(e.id)===String(t.eventId));const players=ev?.players||[],buy=players.reduce((n,p)=>n+(+p.buyin||0),0),rebuy=players.reduce((n,p)=>n+(+p.rebuy||0),0);const rem=t.running?Math.max(0,Math.ceil((t.deadline-Date.now())/1000)):t.remaining;const cur=t.levels[t.index]||[0,0,0,20];return '<div class="card" style="margin:12px 0;border:1px solid #ae9158"><div class="formgrid" style="grid-template-columns:1fr 1fr"><div><label>計時器名稱</label><input value="'+esc(t.name)+'" onchange="epcTimerChange(\''+t.id+'\',\'name\',this.value)"></div><div><label>綁定賽事</label><select onchange="epcTimerChange(\''+t.id+'\',\'eventId\',this.value)"><option value="">請選擇賽事</option>'+events.map(e=>'<option value="'+esc(e.id)+'" '+(String(e.id)===String(t.eventId)?'selected':'')+'>'+esc(e.name||('EPC#'+e.seq+' '+e.level+'限時錦標賽'))+'</option>').join('')+'</select></div></div><h3>'+esc(t.name)+'　<span style="color:#d7b66d">'+String(Math.floor(rem/60)).padStart(2,'0')+':'+String(rem%60).padStart(2,'0')+'</span></h3><p>LEVEL '+(t.index+1)+'｜盲注 '+cur[0]+'/'+cur[1]+'｜前注 '+cur[2]+'｜參賽 '+players.length+' 人｜買入 '+buy+' 組｜重買 '+rebuy+' 組</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary" onclick="epcTimerAction(\''+t.id+'\',\'toggle\')">'+(t.running?'暫停':'開始')+'</button><button onclick="epcTimerAction(\''+t.id+'\',\'prev\')">上一級</button><button onclick="epcTimerAction(\''+t.id+'\',\'next\')">下一級</button><button onclick="epcTimerAction(\''+t.id+'\',\'reset\')">重設</button><button class="danger" onclick="epcTimerDelete(\''+t.id+'\')">刪除</button></div><details style="margin-top:12px"><summary>盲注、獎池、公告及跑馬燈設定</summary><div class="formgrid" style="grid-template-columns:1fr 1fr"><div><label>獎池顯示金額（留空自動）</label><input type="number" value="'+esc(t.pool)+'" onchange="epcTimerChange(\''+t.id+'\',\'pool\',this.value)"></div><div><label>公告文字</label><input value="'+esc(t.announcement)+'" onchange="epcTimerChange(\''+t.id+'\',\'announcement\',this.value)"></div><div><label>跑馬燈</label><input value="'+esc(t.ticker)+'" onchange="epcTimerChange(\''+t.id+'\',\'ticker\',this.value)"></div><div><label>盲注結構（每行小盲,大盲,前注,分鐘）</label><textarea id="levels-'+t.id+'" rows="5">'+esc(t.levels.map(x=>x.join(',')).join('\n'))+'</textarea><button onclick="epcTimerLevels(\''+t.id+'\',document.getElementById(\'levels-'+t.id+'\').value)">儲存盲注結構</button></div></div></details></div>'}).join(''):'<p class="small">尚無計時器，請按「新增計時器」。</p>'};
setInterval(()=>{const box=document.getElementById('epcTimerList');if(!box||!document.getElementById('timers')?.classList.contains('active'))return;for(const t of get()){if(t.running&&Date.now()>=t.deadline){const a=get(),x=a.find(y=>y.id===t.id);if(x){x.running=false;x.remaining=0;localStorage.setItem(KEY,JSON.stringify(a));window.epcTimerRender()}}}},1000);
window.epcTimerRender();
})();