const EPC_DB_ID='1k_7hXkJoDP8nu9kiFkE-NxZhJf4dPQI40p7gBx6RiuI',MEM='Form Responses 1',META='EIGHT_MEMBER_META',EV='EPC_賽事',PL='EPC_賽事玩家',LOG='EPC_CHANGE_LOG';
function doGet(e){return out_(handle_(Object.assign({},e&&e.parameter||{})))} function doPost(e){let b={};try{b=JSON.parse(e.postData.contents||'{}')}catch(_){}return out_(handle_(b))}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)} function db_(){return SpreadsheetApp.openById(EPC_DB_ID)}
function handle_(r){try{switch(String(r.action||'ping')){case'ping':return{ok:true,service:'EPCMAIN',version:'3.0.1'};case'setup':return setup_();case'bootstrap':return bootstrap_(r);case'changes':return changes_(+r.since||0,+r.limit||300);case'member.create':return memberCreate_(r.member||{},r.clientMutationId);case'member.update':return memberUpdate_(r.memberKey,r.patch||{},r.expectedRevision,r.clientMutationId);case'member.delete':return memberDelete_(r.memberKey,r.expectedRevision,r.clientMutationId);case'event.list':return{ok:true,events:listEvents_(r.businessDate||'')};case'player.list':return{ok:true,players:listPlayers_(r.eventId)};default:throw Error('UNKNOWN_ACTION')}}catch(e){return{ok:false,error:String(e.message||e)}}}
function idx_(h,a){for(const n of a){const i=h.indexOf(n);if(i>=0)return i}return-1}
function logSheet_(){const ss=db_();let s=ss.getSheetByName(LOG);if(!s)s=ss.insertSheet(LOG);if(!s.getLastRow())s.appendRow(['cursor','entity','entityKey','op','revision','payloadJson','clientMutationId','createdAt']);return s}
function cursor_(){const p=PropertiesService.getScriptProperties(),n=+p.getProperty('EPC_CURSOR')+1||1;p.setProperty('EPC_CURSOR',String(n));return n}
function log_(entity,key,op,rev,payload,mid){const c=cursor_();logSheet_().appendRow([c,entity,key,op,rev,JSON.stringify(payload||{}),mid||'',new Date()]);return c}
function changes_(since,limit){const s=logSheet_(),last=s.getLastRow();if(last<2)return{ok:true,cursor:since,changes:[]};const v=s.getRange(2,1,last-1,8).getValues(),a=[];let c=since;for(const r of v){if(+r[0]<=since)continue;c=Math.max(c,+r[0]);let p={};try{p=JSON.parse(r[5]||'{}')}catch(_){}a.push({cursor:+r[0],entity:r[1],entityKey:r[2],op:r[3],revision:+r[4],payload:p,clientMutationId:r[6]});if(a.length>=limit)break}return{ok:true,cursor:c,changes:a,hasMore:a.length>=limit}}
function source_(){const s=db_().getSheetByName(MEM),v=s.getDataRange().getValues(),h=v[0].map(String);return{s,v,h,c:{name:idx_(h,['姓名']),id:idx_(h,['POKER FANS ID','POKERFANS ID']),birth:idx_(h,['出生年月日']),phone:idx_(h,['手機號碼']),address:idx_(h,['地址']),ts:idx_(h,['Timestamp','時間戳記'])}}}
function meta_(){return db_().getSheetByName(META)} function mf_(k){const s=meta_(),v=s.getRange(2,1,Math.max(0,s.getLastRow()-1),9).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(k))return{s,row:i+2,r:v[i],rev:+v[i][8]||1};throw Error('MEMBER_NOT_FOUND')}
function srcRow_(x,id){for(let i=1;i<x.v.length;i++)if(String(x.v[i][x.c.id]).trim()===String(id).trim())return i+1;throw Error('MEMBER_NOT_FOUND')}
function mo_(k){const f=mf_(k),x=source_(),rr=srcRow_(x,f.r[1]),r=x.v[rr-1];return{memberKey:k,memberId:String(f.r[1]||''),name:String(r[x.c.name]||''),nickname:String(f.r[3]||''),group:String(f.r[4]||''),status:String(f.r[5]||'active'),birth:x.c.birth>=0?String(r[x.c.birth]||''):'',phone:x.c.phone>=0?String(r[x.c.phone]||''):'',address:x.c.address>=0?String(r[x.c.address]||''):'',revision:f.rev}}
function members_(){const s=meta_();if(s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,6).getValues().filter(r=>r[0]&&String(r[5])!=='deleted').map(r=>mo_(String(r[0])))}
function stale_(a,e){if(e!==undefined&&e!==null&&+a!==+e)throw Error('STALE_WRITE')}
function memberCreate_(m,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const x=source_(),id=String(m.memberId||'').trim().toUpperCase(),name=String(m.name||'').trim();if(!id||!name)throw Error('MEMBER_REQUIRED');for(let i=1;i<x.v.length;i++)if(String(x.v[i][x.c.id]).trim().toUpperCase()===id)throw Error('MEMBER_ID_ALREADY_EXISTS');const row=new Array(x.h.length).fill(''),put=(i,v)=>{if(i>=0)row[i]=v||''};put(x.c.ts,new Date());put(x.c.name,name);put(x.c.id,id);put(x.c.birth,m.birth);put(x.c.phone,m.phone);put(x.c.address,m.address);x.s.appendRow(row);const k='M-'+Utilities.getUuid();meta_().appendRow([k,id,name,m.nickname||'',m.group||'','active',new Date(),new Date(),1]);const member=mo_(k);return{ok:true,member,cursor:log_('member',k,'upsert',1,member,mid)}}finally{l.releaseLock()}}
function memberUpdate_(k,p,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=mf_(k);stale_(f.rev,er);const x=source_(),sr=srcRow_(x,f.r[1]),map={name:x.c.name,memberId:x.c.id,birth:x.c.birth,phone:x.c.phone,address:x.c.address};Object.keys(map).forEach(a=>{if(a in p&&map[a]>=0)x.s.getRange(sr,map[a]+1).setValue(p[a])});if('memberId'in p)f.s.getRange(f.row,2).setValue(String(p.memberId).trim().toUpperCase());if('name'in p)f.s.getRange(f.row,3).setValue(p.name);if('nickname'in p)f.s.getRange(f.row,4).setValue(p.nickname);if('group'in p)f.s.getRange(f.row,5).setValue(p.group);const rev=f.rev+1;f.s.getRange(f.row,8).setValue(new Date());f.s.getRange(f.row,9).setValue(rev);const member=mo_(k);return{ok:true,member,cursor:log_('member',k,'upsert',rev,member,mid)}}finally{l.releaseLock()}}
function memberDelete_(k,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=mf_(k);stale_(f.rev,er);const rev=f.rev+1;f.s.getRange(f.row,6).setValue('deleted');f.s.getRange(f.row,8).setValue(new Date());f.s.getRange(f.row,9).setValue(rev);return{ok:true,cursor:log_('member',k,'delete',rev,{memberKey:k},mid)}}finally{l.releaseLock()}}
function listEvents_(d){const s=db_().getSheetByName(EV);if(!s||s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,20).getValues().filter(r=>r[0]&&String(r[9])!=='deleted'&&(!d||String(r[1])===String(d))).map(r=>({eventId:String(r[0]),businessDate:String(r[1]),name:String(r[2]),startTime:String(r[3]||''),level:String(r[5]||''),buyin:Number(r[6]||0),fee:Number(r[7]||0),jpRate:Number(r[8]||0),status:String(r[9]||'open'),buyinTotal:Number(r[12]||0),buyinAdmin:Number(r[13]||0),rebuyTotal:Number(r[14]||0),rebuyAdmin:Number(r[15]||0),freeAdminFrom:Number(r[16]||11),icmRate:Number(r[17]||3),icmRound:Number(r[18]||100),revision:Number(r[19]||1)}))}
function listPlayers_(id){const s=db_().getSheetByName(PL);if(!s||s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,19).getValues().filter(r=>String(r[0])===String(id)&&String(r[8])!=='deleted').map(r=>({eventId:String(r[0]),memberKey:String(r[1]),memberId:String(r[2]),name:String(r[3]),entries:+r[4]||1,discount:+r[5]||0,group:String(r[6]||''),chips:+r[7]||0,status:String(r[8]||'active'),earlyDiscount:+r[11]||0,lateDiscount:+r[12]||0,rebuyDiscount:+r[13]||0,entryDiscount:+r[14]||0,otherDiscount:+r[15]||0,buyin:+r[16]||1,rebuy:+r[17]||0,revision:+r[18]||1}))}
function bootstrap_(r){return{ok:true,apiVersion:'3.0.1',cursor:+PropertiesService.getScriptProperties().getProperty('EPC_CURSOR')||0,settings:{businessStart:'16:00',businessEnd:'07:00'},members:members_(),events:listEvents_(r.businessDate||''),summary:{memberCount:members_().length,monthNewMembers:0}}}
function setup_(){const ss=db_(),m=ss.getSheetByName(META),e=ss.getSheetByName(EV),p=ss.getSheetByName(PL);if(!m||!e||!p)throw Error('REQUIRED_SHEET_MISSING');[[m,9],[e,20],[p,19]].forEach(([s,c])=>{if(s.getMaxColumns()<c)s.insertColumnsAfter(s.getMaxColumns(),c-s.getMaxColumns());s.getRange(1,c).setValue('revision');if(s.getLastRow()>1){const rg=s.getRange(2,c,s.getLastRow()-1,1),v=rg.getValues();v.forEach(r=>{if(!+r[0])r[0]=1});rg.setValues(v)}});logSheet_();PropertiesService.getScriptProperties().setProperty('EPC_CURSOR','0');return{ok:true,setup:true}}
