const EPC_DB_ID='1k_7hXkJoDP8nu9kiFkE-NxZhJf4dPQI40p7gBx6RiuI',MEM='Form Responses 1',META='EIGHT_MEMBER_META',EV='EPC_賽事',PL='EPC_賽事玩家',LOG='EPC_CHANGE_LOG',ACC='EPC_帳務';
function doGet(e){return out_(handle_(Object.assign({},e&&e.parameter||{})))} function doPost(e){let b={};try{b=JSON.parse(e.postData.contents||'{}')}catch(_){}return out_(handle_(b))}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)} function db_(){return SpreadsheetApp.openById(EPC_DB_ID)}
function handle_(r){try{switch(String(r.action||'ping')){case'ping':return{ok:true,service:'EPCMAIN',version:'3.0.1'};case'setup':return setup_();case'bootstrap':return bootstrap_(r);case'changes':return changes_(+r.since||0,+r.limit||300);case'member.create':return memberCreate_(r.member||{},r.clientMutationId);case'member.update':return memberUpdate_(r.memberKey,r.patch||{},r.expectedRevision,r.clientMutationId);case'member.delete':return memberDelete_(r.memberKey,r.expectedRevision,r.clientMutationId);case'settings.update':return settingsUpdate_(r.settings||{});case'event.list':return{ok:true,events:listEvents_(r.businessDate||'')};case'event.snapshot':return eventSnapshot_(r.eventId);case'event.settle':return eventSettle_(r.eventId,r.expectedRevision,r.clientMutationId);case'accounting.list':return accountingList_(r.startDate||'',r.endDate||'');case'settlement.report':return settlementReport_(r.startDate||'',r.endDate||'',r.businessDate||'');case'dashboard.summary':return dashboardSummary_(r.startDate||'',r.endDate||'');case'event.create':return eventCreate_(r.event||{},r.clientMutationId);case'event.update':return eventUpdate_(r.eventId,r.patch||{},r.expectedRevision,r.clientMutationId);case'event.delete':return eventDelete_(r.eventId,r.expectedRevision,r.clientMutationId);case'player.list':return{ok:true,players:listPlayers_(r.eventId)};case'player.add':return playerAdd_(r.eventId,r.memberKey,r.player||{},r.clientMutationId);case'player.update':return playerUpdate_(r.eventId,r.memberKey,r.patch||{},r.expectedRevision,r.clientMutationId);case'player.delete':return playerDelete_(r.eventId,r.memberKey,r.expectedRevision,r.clientMutationId);default:throw Error('UNKNOWN_ACTION')}}catch(e){return{ok:false,error:String(e.message||e)}}}
function idx_(h,a){for(const n of a){const i=h.indexOf(n);if(i>=0)return i}return-1}
function logSheet_(){const ss=db_();let s=ss.getSheetByName(LOG);if(!s)s=ss.insertSheet(LOG);if(!s.getLastRow())s.appendRow(['cursor','entity','entityKey','op','revision','payloadJson','clientMutationId','createdAt']);return s}
function cursor_(){const p=PropertiesService.getScriptProperties(),n=+p.getProperty('EPC_CURSOR')+1||1;p.setProperty('EPC_CURSOR',String(n));return n}
function log_(entity,key,op,rev,payload,mid){const c=cursor_();logSheet_().appendRow([c,entity,key,op,rev,JSON.stringify(payload||{}),mid||'',new Date()]);return c}
function changes_(since,limit){const s=logSheet_(),last=s.getLastRow();if(last<2)return{ok:true,cursor:since,changes:[]};const v=s.getRange(2,1,last-1,8).getValues(),a=[];let c=since;for(const r of v){if(+r[0]<=since)continue;c=Math.max(c,+r[0]);let p={};try{p=JSON.parse(r[5]||'{}')}catch(_){}a.push({cursor:+r[0],entity:r[1],entityKey:r[2],op:r[3],revision:+r[4],payload:p,clientMutationId:r[6]});if(a.length>=limit)break}return{ok:true,cursor:c,changes:a,hasMore:a.length>=limit}}
function source_(){const s=db_().getSheetByName(MEM),v=s.getDataRange().getValues(),h=v[0].map(String);return{s,v,h,c:{name:idx_(h,['姓名']),id:idx_(h,['POKER FANS ID','POKERFANS ID']),birth:idx_(h,['出生年月日']),phone:idx_(h,['手機號碼']),address:idx_(h,['地址']),ts:idx_(h,['Timestamp','時間戳記'])}}}
function meta_(){return db_().getSheetByName(META)} function mf_(k){const s=meta_(),v=s.getRange(2,1,Math.max(0,s.getLastRow()-1),9).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(k))return{s,row:i+2,r:v[i],rev:+v[i][8]||1};throw Error('MEMBER_NOT_FOUND')}
function srcRow_(x,id){for(let i=1;i<x.v.length;i++)if(String(x.v[i][x.c.id]).trim()===String(id).trim())return i+1;throw Error('MEMBER_NOT_FOUND')}
function mo_(k){const f=mf_(k),x=source_(),rr=srcRow_(x,f.r[1]),r=x.v[rr-1];return{memberKey:k,memberId:String(f.r[1]||''),name:String(r[x.c.name]||''),nickname:String(f.r[3]||''),group:String(f.r[4]||''),status:String(f.r[5]||'active'),birth:x.c.birth>=0?String(r[x.c.birth]||''):'',phone:x.c.phone>=0?String(r[x.c.phone]||''):'',address:x.c.address>=0?String(r[x.c.address]||''):'',revision:f.rev}}
function members_(){const s=meta_();if(s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,6).getValues().filter(r=>r[0]&&String(r[5])!=='deleted').map(r=>mo_(String(r[0])))}
function stale_(a,e){if(e!==undefined&&e!==null&&+a!==+e)throw Error('STALE_WRITE')}
function memberCreate_(m,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const x=source_(),id=String(m.memberId||'').trim().toUpperCase(),name=String(m.name||'').trim();if(!id||!name)throw Error('MEMBER_REQUIRED');for(let i=1;i<x.v.length;i++)if(String(x.v[i][x.c.id]).trim().toUpperCase()===id)throw Error('MEMBER_ID_ALREADY_EXISTS');const row=new Array(x.h.length).fill(''),put=(i,v)=>{if(i>=0)row[i]=v||''};put(x.c.ts,new Date());put(x.c.name,name);put(x.c.id,id);put(x.c.birth,m.birth);put(x.c.phone,m.phone);put(x.c.address,m.address);x.s.appendRow(row);const k='M-'+Utilities.getUuid();meta_().appendRow([k,id,name,m.nickname||'',m.group||'','active',new Date(),new Date(),1]);const member=mo_(k);return{ok:true,member,cursor:log_('member',k,'upsert',1,member,mid)}}finally{l.releaseLock()}}
function memberUpdate_(k,p,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=mf_(k);stale_(f.rev,er);const x=source_(),sr=srcRow_(x,f.r[1]),map={name:x.c.name,memberId:x.c.id,birth:x.c.birth,phone:x.c.phone,address:x.c.address};Object.keys(map).forEach(a=>{if(a in p&&map[a]>=0)x.s.getRange(sr,map[a]+1).setValue(p[a])});if('memberId'in p)f.s.getRange(f.row,2).setValue(String(p.memberId).trim().toUpperCase());if('name'in p)f.s.getRange(f.row,3).setValue(p.name);if('nickname'in p)f.s.getRange(f.row,4).setValue(p.nickname);if('group'in p)f.s.getRange(f.row,5).setValue(p.group);const rev=f.rev+1;f.s.getRange(f.row,8).setValue(new Date());f.s.getRange(f.row,9).setValue(rev);const member=mo_(k);return{ok:true,member,cursor:log_('member',k,'upsert',rev,member,mid)}}finally{l.releaseLock()}}
function memberDelete_(k,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=mf_(k);stale_(f.rev,er);const rev=f.rev+1;f.s.getRange(f.row,6).setValue('deleted');f.s.getRange(f.row,8).setValue(new Date());f.s.getRange(f.row,9).setValue(rev);return{ok:true,cursor:log_('member',k,'delete',rev,{memberKey:k},mid)}}finally{l.releaseLock()}}
function listEvents_(d){const s=db_().getSheetByName(EV);if(!s||s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,20).getValues().filter(r=>r[0]&&String(r[9])!=='deleted'&&(!d||String(r[1])===String(d))).map(r=>({eventId:String(r[0]),businessDate:String(r[1]),name:String(r[2]),startTime:String(r[3]||''),level:String(r[5]||''),buyin:Number(r[6]||0),fee:Number(r[7]||0),jpRate:Number(r[8]||0),status:String(r[9]||'open'),buyinTotal:Number(r[12]||0),buyinAdmin:Number(r[13]||0),rebuyTotal:Number(r[14]||0),rebuyAdmin:Number(r[15]||0),freeAdminFrom:Number(r[16]||11),icmRate:Number(r[17]||3),icmRound:Number(r[18]||100),revision:Number(r[19]||1)}))}
function listPlayers_(id){const s=db_().getSheetByName(PL);if(!s||s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,19).getValues().filter(r=>String(r[0])===String(id)&&String(r[8])!=='deleted').map(r=>({eventId:String(r[0]),memberKey:String(r[1]),memberId:String(r[2]),name:String(r[3]),entries:+r[4]||1,discount:+r[5]||0,group:String(r[6]||''),chips:+r[7]||0,status:String(r[8]||'active'),earlyDiscount:+r[11]||0,lateDiscount:+r[12]||0,rebuyDiscount:+r[13]||0,entryDiscount:+r[14]||0,otherDiscount:+r[15]||0,buyin:+r[16]||1,rebuy:+r[17]||0,revision:+r[18]||1}))}
function bootstrap_(r){return{ok:true,apiVersion:'3.0.1',cursor:+PropertiesService.getScriptProperties().getProperty('EPC_CURSOR')||0,settings:settings_(),members:members_(),events:listEvents_(r.businessDate||''),summary:{memberCount:members_().length,monthNewMembers:0}}}
function setup_(){const ss=db_(),m=ss.getSheetByName(META),e=ss.getSheetByName(EV),p=ss.getSheetByName(PL);if(!m||!e||!p)throw Error('REQUIRED_SHEET_MISSING');[[m,9],[e,20],[p,19]].forEach(([s,c])=>{if(s.getMaxColumns()<c)s.insertColumnsAfter(s.getMaxColumns(),c-s.getMaxColumns());s.getRange(1,c).setValue('revision');if(s.getLastRow()>1){const rg=s.getRange(2,c,s.getLastRow()-1,1),v=rg.getValues();v.forEach(r=>{if(!+r[0])r[0]=1});rg.setValues(v)}});logSheet_();PropertiesService.getScriptProperties().setProperty('EPC_CURSOR','0');return{ok:true,setup:true}}

function settingsUpdate_(p){const ss=db_();let sh=ss.getSheetByName('EPC_系統設定');if(!sh){sh=ss.insertSheet('EPC_系統設定');sh.appendRow(['設定鍵','設定值','說明','最後更新時間'])}const rows=sh.getDataRange().getDisplayValues(),allowed={businessStart:'營業開始時間',businessEnd:'營業結束時間'};Object.keys(allowed).forEach(k=>{if(!(k in p))return;const val=String(p[k]||'');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(val))throw Error('INVALID_TIME');let row=0;for(let i=1;i<rows.length;i++)if(rows[i][0]===k){row=i+1;break}if(row)sh.getRange(row,2,1,3).setValues([[val,allowed[k],new Date()]]);else sh.appendRow([k,val,allowed[k],new Date()])});return{ok:true,settings:settings_()}}
function settings_(){const sh=db_().getSheetByName('EPC_系統設定'),o={businessStart:'16:00',businessEnd:'07:00'};if(sh&&sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,2).getDisplayValues().forEach(r=>{if(r[0])o[r[0]]=r[1]});return o}
function ef_(id){const sh=db_().getSheetByName(EV);if(!sh||sh.getLastRow()<2)throw Error('EVENT_NOT_FOUND');const v=sh.getRange(2,1,sh.getLastRow()-1,20).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(id))return{sh,row:i+2,r:v[i],rev:+v[i][19]||1};throw Error('EVENT_NOT_FOUND')}
function eo_(id){const f=ef_(id),r=f.r;return{eventId:String(r[0]),businessDate:String(r[1]),name:String(r[2]),startTime:String(r[3]||''),regClose:String(r[4]||''),level:String(r[5]||''),buyin:+r[6]||0,fee:+r[7]||0,jpRate:+r[8]||0,status:String(r[9]||'open'),buyinTotal:+r[12]||0,buyinAdmin:+r[13]||0,rebuyTotal:+r[14]||0,rebuyAdmin:+r[15]||0,freeAdminFrom:+r[16]||11,icmRate:+r[17]||3,icmRound:+r[18]||100,revision:+r[19]||1}}
function eventCreate_(e,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{if(!String(e.name||'').trim())throw Error('EVENT_NAME_REQUIRED');const sh=db_().getSheetByName(EV),id='E-'+Utilities.getUuid(),rev=1;sh.appendRow([id,e.businessDate||'',String(e.name).trim(),e.startTime||'',e.regClose||'',e.level||'custom',+e.buyin||0,+e.fee||0,+e.jpRate||0,'open',new Date(),new Date(),+e.buyinTotal||0,+e.buyinAdmin||0,+e.rebuyTotal||0,+e.rebuyAdmin||0,+e.freeAdminFrom||11,+e.icmRate||3,+e.icmRound||100,rev]);const event=eo_(id);return{ok:true,event,cursor:log_('event',id,'upsert',rev,event,mid)}}finally{l.releaseLock()}}
function eventUpdate_(id,p,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=ef_(id);stale_(f.rev,er);const map={businessDate:2,name:3,startTime:4,regClose:5,level:6,buyin:7,fee:8,jpRate:9,status:10,buyinTotal:13,buyinAdmin:14,rebuyTotal:15,rebuyAdmin:16,freeAdminFrom:17,icmRate:18,icmRound:19};Object.keys(map).forEach(k=>{if(k in p)f.sh.getRange(f.row,map[k]).setValue(p[k])});const rev=f.rev+1;f.sh.getRange(f.row,12).setValue(new Date());f.sh.getRange(f.row,20).setValue(rev);const event=eo_(id);return{ok:true,event,cursor:log_('event',id,'upsert',rev,event,mid)}}finally{l.releaseLock()}}
function eventDelete_(id,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=ef_(id);stale_(f.rev,er);const rev=f.rev+1;f.sh.getRange(f.row,10).setValue('deleted');f.sh.getRange(f.row,12).setValue(new Date());f.sh.getRange(f.row,20).setValue(rev);return{ok:true,cursor:log_('event',id,'delete',rev,{eventId:id},mid)}}finally{l.releaseLock()}}
function pf_(eventId,key){const sh=db_().getSheetByName(PL);if(!sh||sh.getLastRow()<2)throw Error('EVENT_PLAYER_NOT_FOUND');const v=sh.getRange(2,1,sh.getLastRow()-1,19).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(eventId)&&String(v[i][1])===String(key)&&String(v[i][8])!=='deleted')return{sh,row:i+2,r:v[i],rev:+v[i][18]||1};throw Error('EVENT_PLAYER_NOT_FOUND')}
function po_(eventId,key){const f=pf_(eventId,key),r=f.r;return{eventId:String(r[0]),memberKey:String(r[1]),memberId:String(r[2]),name:String(r[3]),entries:+r[4]||1,discount:+r[5]||0,group:String(r[6]||''),chips:+r[7]||0,status:String(r[8]||'active'),earlyDiscount:+r[11]||0,lateDiscount:+r[12]||0,rebuyDiscount:+r[13]||0,entryDiscount:+r[14]||0,otherDiscount:+r[15]||0,buyin:+r[16]||1,rebuy:+r[17]||0,revision:+r[18]||1}}
function playerAdd_(eventId,key,p,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{ef_(eventId);try{pf_(eventId,key);throw Error('PLAYER_ALREADY_IN_EVENT')}catch(e){if(e.message!=='EVENT_PLAYER_NOT_FOUND')throw e}const m=mo_(key),sh=db_().getSheetByName(PL),rev=1;sh.appendRow([eventId,key,m.memberId,m.name,1,0,p.group||m.group||'',0,'active',new Date(),new Date(),0,0,0,0,0,1,0,rev]);const player=po_(eventId,key),ek=eventId+'|'+key;return{ok:true,player,cursor:log_('player',ek,'upsert',rev,player,mid)}}finally{l.releaseLock()}}
function playerUpdate_(eventId,key,p,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=pf_(eventId,key);stale_(f.rev,er);let buyin='buyin'in p?Math.max(0,+p.buyin||0):(+f.r[16]||1),rebuy='rebuy'in p?Math.max(0,+p.rebuy||0):(+f.r[17]||0);const map={discount:6,group:7,chips:8,status:9,earlyDiscount:12,lateDiscount:13,rebuyDiscount:14,entryDiscount:15,otherDiscount:16,buyin:17,rebuy:18};Object.keys(map).forEach(k=>{if(k in p)f.sh.getRange(f.row,map[k]).setValue(p[k])});f.sh.getRange(f.row,5).setValue(buyin+rebuy);const rev=f.rev+1;f.sh.getRange(f.row,11).setValue(new Date());f.sh.getRange(f.row,19).setValue(rev);const player=po_(eventId,key),ek=eventId+'|'+key;return{ok:true,player,cursor:log_('player',ek,'upsert',rev,player,mid)}}finally{l.releaseLock()}}
function playerDelete_(eventId,key,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const f=pf_(eventId,key);stale_(f.rev,er);const rev=f.rev+1;f.sh.getRange(f.row,9).setValue('deleted');f.sh.getRange(f.row,11).setValue(new Date());f.sh.getRange(f.row,19).setValue(rev);const ek=eventId+'|'+key;return{ok:true,cursor:log_('player',ek,'delete',rev,{eventId:eventId,memberKey:key},mid)}}finally{l.releaseLock()}}

function eventSnapshot_(id){
 const e=eo_(id),ps=listPlayers_(id);let buyins=0,rebuys=0,early=0,late=0,other=0,rebuyDisc=0,entryDisc=0;
 ps.forEach(p=>{const b=Math.max(0,+p.buyin||1),rb=Math.max(0,+p.rebuy||0);buyins+=b;rebuys+=rb;early+=+p.earlyDiscount||0;late+=+p.lateDiscount||0;other+=+p.otherDiscount||0;rebuyDisc+=rb*(+e.rebuyAdmin||0)/2;entryDisc+=Math.max(0,b+rb-Math.max(0,(+e.freeAdminFrom||11)-1))*(+e.rebuyAdmin||0)/2});
 const totalEntries=buyins+rebuys,totalGross=buyins*(+e.buyinTotal||0)+rebuys*(+e.rebuyTotal||0),adminGross=buyins*(+e.buyinAdmin||0)+rebuys*(+e.rebuyAdmin||0),discounts=early+late+rebuyDisc+entryDisc+other,jp=Math.floor(adminGross*(+e.jpRate||0)/100);
 const prizeBase=buyins*Math.max(0,(+e.buyinTotal||0)-(+e.buyinAdmin||0))+rebuys*Math.max(0,(+e.rebuyTotal||0)-(+e.rebuyAdmin||0)),unit=Math.max(1,+e.icmRound||100),prizePool=Math.floor((prizeBase*(1-(+e.icmRate||0)/100))/unit)*unit;
 return{ok:true,snapshot:{event:e,players:ps,summary:{participants:ps.length,rebuyPeople:ps.filter(p=>(+p.rebuy||0)>0).length,totalEntries,totalGross,earlyDiscount:early,lateDiscount:late,rebuyDiscount:rebuyDisc,entryDiscount:entryDisc,otherDiscount:other,totalDiscount:discounts,prizePool,adminGross,adminNet:Math.max(0,adminGross-discounts),jp}}}
}

function acc_(){const ss=db_();let sh=ss.getSheetByName(ACC);if(!sh){sh=ss.insertSheet(ACC);sh.appendRow(['eventId','businessDate','eventName','level','participants','rebuyPeople','totalEntries','totalGross','earlyDiscount','lateDiscount','rebuyDiscount','entryDiscount','otherDiscount','totalDiscount','prizePool','adminGross','adminNet','jp','status','createdAt','updatedAt','revision'])}return sh}
function af_(id){const sh=acc_();if(sh.getLastRow()<2)return null;const v=sh.getRange(2,1,sh.getLastRow()-1,22).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(id))return{sh,row:i+2,r:v[i],rev:+v[i][21]||1};return null}
function ao_(r){return{eventId:String(r[0]),businessDate:String(r[1]),eventName:String(r[2]),level:String(r[3]),participants:+r[4]||0,rebuyPeople:+r[5]||0,totalEntries:+r[6]||0,totalGross:+r[7]||0,earlyDiscount:+r[8]||0,lateDiscount:+r[9]||0,rebuyDiscount:+r[10]||0,entryDiscount:+r[11]||0,otherDiscount:+r[12]||0,totalDiscount:+r[13]||0,prizePool:+r[14]||0,adminGross:+r[15]||0,adminNet:+r[16]||0,jp:+r[17]||0,status:String(r[18]||'settled'),revision:+r[21]||1}}
function eventSettle_(id,er,mid){const l=LockService.getScriptLock();l.waitLock(8000);try{const snap=eventSnapshot_(id).snapshot,e=snap.event,z=snap.summary,old=af_(id);if(old&&er!==undefined&&er!==null)stale_(old.rev,er);const rev=old?old.rev+1:1,now=new Date(),row=[id,e.businessDate,e.name,e.level,z.participants,z.rebuyPeople,z.totalEntries,z.totalGross,z.earlyDiscount,z.lateDiscount,z.rebuyDiscount,z.entryDiscount,z.otherDiscount,z.totalDiscount,z.prizePool,z.adminGross,z.adminNet,z.jp,'settled',old?old.r[19]:now,now,rev];if(old)old.sh.getRange(old.row,1,1,22).setValues([row]);else acc_().appendRow(row);const f=ef_(id);f.sh.getRange(f.row,10).setValue('settled');const evrev=f.rev+1;f.sh.getRange(f.row,12).setValue(now);f.sh.getRange(f.row,20).setValue(evrev);const accounting=ao_(row),cursor=log_('accounting',id,'upsert',rev,accounting,mid);log_('event',id,'upsert',evrev,eo_(id),mid);return{ok:true,accounting,snapshot:snap,cursor}}finally{l.releaseLock()}}
function accountingList_(a,b){const sh=acc_();if(sh.getLastRow()<2)return{ok:true,rows:[]};const rows=sh.getRange(2,1,sh.getLastRow()-1,22).getValues().filter(r=>r[0]&&String(r[18])!=='deleted'&&(!a||String(r[1])>=a)&&(!b||String(r[1])<=b)).map(ao_);return{ok:true,rows}}
function dashboardSummary_(a,b){const rows=accountingList_(a,b).rows,o={eventCount:rows.length,totalGross:0,totalDiscount:0,prizePool:0,adminGross:0,adminNet:0,jp:0,participants:0,totalEntries:0,levels:{}};rows.forEach(r=>{o.totalGross+=r.totalGross;o.totalDiscount+=r.totalDiscount;o.prizePool+=r.prizePool;o.adminGross+=r.adminGross;o.adminNet+=r.adminNet;o.jp+=r.jp;o.participants+=r.participants;o.totalEntries+=r.totalEntries;o.levels[r.level]=(o.levels[r.level]||0)+1});return{ok:true,summary:o,rows}}

function settlementReport_(a,b,d){
 const rows=accountingList_(d||a,d||b).rows,events=[],groups={},members={};
 rows.forEach(acc=>{let ps=[];try{ps=listPlayers_(acc.eventId)}catch(_){};events.push({eventId:acc.eventId,businessDate:acc.businessDate,eventName:acc.eventName,level:acc.level,participants:acc.participants,totalGross:acc.totalGross,prizePool:acc.prizePool,adminNet:acc.adminNet,jp:acc.jp});ps.forEach(p=>{const g=String(p.group||'未分組').trim()||'未分組',key=p.memberKey||p.memberId,paid=(+p.buyin||1)*(+ef_(acc.eventId).r[12]||0)+(+p.rebuy||0)*(+ef_(acc.eventId).r[14]||0)-(+p.earlyDiscount||0)-(+p.lateDiscount||0)-(+p.rebuyDiscount||0)-(+p.entryDiscount||0)-(+p.otherDiscount||0);if(!groups[g])groups[g]={group:g,members:{},totalPaid:0,totalPrize:0,net:0};if(!groups[g].members[key])groups[g].members[key]={memberKey:p.memberKey,memberId:p.memberId,name:p.name,paid:0,prize:0,net:0,events:0};const m=groups[g].members[key];m.paid+=paid;m.events++;groups[g].totalPaid+=paid;members[key]=true})});
 Object.values(groups).forEach(g=>{g.members=Object.values(g.members);g.net=g.totalPrize-g.totalPaid});
 return{ok:true,report:{startDate:d||a,endDate:d||b,eventCount:events.length,memberCount:Object.keys(members).length,totalPaid:Object.values(groups).reduce((n,g)=>n+g.totalPaid,0),totalPrize:rows.reduce((n,r)=>n+r.prizePool,0),events,groups:Object.values(groups)}}
}
